- eox_nelp/course_api/serializers.py
Add parser to retrieve the data of the HTML course-overview.
Also, the endpoint was modified to show the new overview object.
> feat: add parser to course-overview.

- CHANGELOG.rst
- README.rst
- eox_nelp/__init__.py
- setup.cfg
> Jlc/bump version v0.1.0

- CHANGELOG.rst
- README.rst
- eox_nelp/__init__.py
- setup.cfg
> Jlc/bump version v0.2.0

- eox_nelp/course_api/serializers.py
This is the first approximation of the teacher images course url. This is based on the information provided on the course about page. 
https://edunext.atlassian.net/browse/NELP-253?atlOrigin=eyJpIjoiMTY4YzYyZDFjN2I0NDkyMmE3OGVmZjA5YjQ2ZjJjZjgiLCJwIjoiaiJ9
> feat: add instructor img link from about overview

- eox_nelp/course_api/__init__.py
Update based in the maple version of this file.
https://github.com/openedx/edx-platform/blob/open-release/maple.3/lms/djangoapps/course_api/__init__.py
> feat: update waffeswitch import  change from maple

- eox_nelp/course_api/urls.py
- eox_nelp/urls.py
Remove redundant urls since those endpoints are accessible in the platform
> fix: Remove redundant urls

- CHANGELOG.rst
- eox_nelp/__init__.py
- setup.cfg
Bump version to maple -> v1.0.0
> Jlc/bump v1.0.0

- eox_nelp/edxapp_wrapper/backends/site_configuration_m_v1.py
- eox_nelp/edxapp_wrapper/backends/user_api_m_v1.py
- eox_nelp/edxapp_wrapper/backends/user_authn_m_v1.py
- eox_nelp/edxapp_wrapper/site_configuration.py
- eox_nelp/edxapp_wrapper/user_api.py
- eox_nelp/edxapp_wrapper/user_authn.py
- eox_nelp/middleware.py
- eox_nelp/settings/common.py
Add middleware file that includes anew class that allows to extend the registration fields based on tenant settings
> feat: Add middleware file 

- docs/decisions/0001-course-experience.rst
This describes briefly models and APIs that are necessary to complete this requirements https://edunext.atlassian.net/browse/NELP-294
> feat: add experience ADR

- eox_nelp/apps.py
- eox_nelp/receivers.py
> feat: add receivers file and connect basi function to signals

- Makefile
- eox_nelp/api_clients/futurex.py
- eox_nelp/api_clients/tests/tests_futurex.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
- requirements/base.in
- requirements/base.txt
- requirements/pip-tools.txt
- requirements/test.txt
- requirements/tox.txt
This includes the api client to communicate with futurex services, this just include one case, that is the enrollment progress
it is not possible since we don't have credentials
Epic link https://edunext.atlassian.net/jira/software/c/projects/NELP/issues/NELP-371
> feat: add futurex api client

- eox_nelp/management/commands/notify_course_due_dates.py
- eox_nelp/management/commands/tests/test_check_notify_course_due_dates.py
- setup.cfg
Management command to check course due dates. If conditions are
satisfied, manage the delivery with notify method of the UpcomingCourseDueDate object.
To run it use:
`./manage lms notify_course_due_dates`.
- feat: add base command to check and delivery sent
- this manages the delivery of the upcoming course due dates Missing to add the change the model notify method.
- feat: add test for command check_notify_due
> feat: add command to check UpcomingCourseDueDate

- MANIFEST.in
- eox_nelp/course_experience/api/v1/views.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
- requirements/eox-audit-model.in
- setup.py
feat: add eox-audit to course xp views
No eox_audit records
> feat: add eox-audit to course xp views

- eox_nelp/stats/templates/tenant_stats.html
- eox_nelp/stats/tests/test_views.py
- eox_nelp/stats/views.py
This changes the format of the query params from camel case to snake case
> feat: use query params in snake case

- eox_nelp/stats/urls.py
> fix: set right doc-string

- eox_nelp/course_experience/admin.py
This includes the searching and filtering functionality for FeedbackCourseAdmin
1 Go to admin and open your eyes
> feat: add feedback admin fields

- eox_nelp/apps.py
- eox_nelp/edxapp_wrapper/backends/student_m_v1.py
- eox_nelp/edxapp_wrapper/student.py
- eox_nelp/edxapp_wrapper/test_backends/student_m_v1.py
- eox_nelp/init_pipeline.py
This limits the gender options to Male and Female, and also includes a new pipeline flow for the methods that must run after the app registration
1. checkout this branch
2. go to the register page 
3. Verify the gender options
> feat: add gender choices patch

- eox_nelp/api_clients/certificates.py
- eox_nelp/api_clients/tests/tests_certificates.py
- eox_nelp/settings/test.py
This is a first version if the certificates APIclient ,however this is just an initial approach since that must be improved when we have more details about the API.
[issue](https://edunext.atlassian.net/browse/FUTUREX-478)
> feat: add certificates api client

- eox_nelp/api_clients/certificates.py
Set the API path with the right value.
> fix: change certificates path

- eox_nelp/api_clients/certificates.py
Previous structure was an outdated example, this implements the new structure and allow to set the metadata by settings
> fix: update certificates api_client data structure

- .github/workflows/strain_dispatcher.yml
Describe what this pull request changes, and why. Include implications for people using this change.
Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
> chore: allow closed types

- eox_nelp/openedx_filters/tests/xapi/tests_filters.py
- eox_nelp/openedx_filters/xapi/filters.py
This version updates the filters signature in order to support transformer arguments https://github.com/openedx/event-routing-backends/pull/374
> chore: update filters

- eox_nelp/tests/test_utils.py
- eox_nelp/utils.py
Validate markdown type, just string types are valid
> fix: validate markdown type

- eox_nelp/edxapp_wrapper/backends/event_routing_backends_m_v1.py
- eox_nelp/edxapp_wrapper/event_routing_backends.py
- eox_nelp/edxapp_wrapper/test_backends/event_routing_backends_m_v1.py
- eox_nelp/init_pipeline.py
- eox_nelp/openedx_filters/tests/xapi/tests_filters.py
- eox_nelp/openedx_filters/xapi/filters.py
- eox_nelp/processors/tests/xapi/event_transformers/tests_initialized_events.py
- eox_nelp/processors/xapi/constants.py
- eox_nelp/processors/xapi/event_transformers/__init__.py
- eox_nelp/processors/xapi/event_transformers/initialized_events.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
- eox_nelp/tests/test_init_pipeline.py
This add the transformer for the event added [here](https://github.com/eduNEXT/eox-nelp/pull/112)
1. Set settings  
```
EVENT_TRACKING_BACKENDS["xapi"] = {
"ENGINE": "eventtracking.backends.async_routing.AsyncRoutingBackend",
"OPTIONS": {
"backend_name": "xapi",
"processors": [
{
"ENGINE": "eventtracking.processors.whitelist.NameWhitelistProcessor",
"OPTIONS": {
"whitelist": [
"nelc.eox_nelp.initialized.course",
]
}
}
],
"backends": {
"xapi": {
"ENGINE": "event_routing_backends.backends.events_router.EventsRouter",
"OPTIONS": {
"processors": [
{
"ENGINE": "event_routing_backends.processors.xapi.transformer_processor.XApiProcessor",
"OPTIONS": {}
}
],
"backend_name": "xapi"
}
}
}
}
}
EVENT_TRACKING_BACKENDS.pop("caliper", None)
OPEN_EDX_FILTERS_CONFIG = { …
```
> feat: add initialized event transformer

- eox_nelp/course_experience/models.py
- eox_nelp/course_experience/tests/tests_models.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
- eox_nelp/tests/test_utils.py
- eox_nelp/utils.py
This add feedback events
1. go to the admin panel and create and save  Feedback course and unit records
2. check logs
> feat: add feedback events

- eox_nelp/processors/tests/xapi/event_transformers/tests_initialized_events.py
- eox_nelp/processors/tests/xapi/mixins.py
- eox_nelp/processors/tests/xapi/tests_mixins.py
- eox_nelp/processors/xapi/event_transformers/initialized_events.py
- eox_nelp/processors/xapi/mixins.py
- eox_nelp/signals/tests/test_receivers.py
This is a refactor of https://github.com/eduNEXT/eox-nelp/pull/114
Follow the instructions of https://github.com/eduNEXT/eox-nelp/pull/114
> refactor: implement course object mixin

- eox_nelp/apps.py
- eox_nelp/signals/receivers.py
- eox_nelp/signals/tests/test_receivers.py
This updates the tracker context in asynchronous processes.
This is not easy to test locally since this depends on the lms worker, and the tutor worker is not friendly with the dev mode, so the first step is to have a functional environment where the code could be updated easily, then yopu can follow the next steps
1. Run a task that emits an event , in my case  I'm using completion-aggregators library which emits this [event](https://github.com/nelc/openedx-completion-aggregator/blob/ead8f61b1081a87aa7e37887d82724f807320129/completion_aggregator/models.py#L175) in an async mode when I submit a problem
2. Check the worker logs 
3. Verify the context key
Execute the previous steps with this and the master in order to compare both results
Include anything else that will help reviewers and …
> feat: updates asynchronous tracker context

- eox_nelp/openedx_filters/tests/xapi/tests_filters.py
- eox_nelp/openedx_filters/xapi/filters.py
This adds extra fields based on the settings to the context key of any statement 
1 include the extra settings
```
"XAPI_EXTRA_CONTEXT": {
"extensions": {
"https://nelc.gov.sa/extensions/platform": {
"name": {
"ar-SA": "\u0627\u0644\u062a\u0642\u0646\u064a\u0627\u062a \u0627\u0644\u0645\u062a\u0642\u062f\u0645\u0629 \u0644\u0644\u062a\u062f\u0631\u064a\u0628",
"en-US": "Leading Tech for Training"
}
}
},
"instructor": {
"mbox": "mailto:ik@example.com",
"name": " Ibrahim Khalid "
},
"language": "ar-SA",
"platform": "SREI"
},
```
2. raised any event
3. check the context filed
- Any special concerns or limitations? For example: deprecations, migrations, …
> feat: add context filter

- eox_nelp/openedx_filters/tests/xapi/tests_filters.py
- eox_nelp/openedx_filters/xapi/filters.py
This adds the http://id.tincanapi.com/extension/jws-certificate-location filed to the statement context
1. Add the filter settings
```
OPEN_EDX_FILTERS_CONFIG = {
"event_routing_backends.processors.xapi.transformer.xapi_transformer.get_context": {
"pipeline": [
"eox_nelp.openedx_filters.xapi.filters.XApiContextFilter",
"eox_nelp.openedx_filters.xapi.filters.XApiCertificateContextFilter",
],
"fail_silently": False,
},
}
EVENT_TRACKING_BACKENDS["xapi"] = {
"ENGINE": "eventtracking.backends.async_routing.AsyncRoutingBackend",
"OPTIONS": {
"backend_name": "xapi",
"processors": [
{
"ENGINE": "eventtracking.processors.whitelist.NameWhitelistProcessor",
"OPTIONS": {
"whitelist": [
"edx.certificate.created",
]
}
}
],
"backends": {
"xapi": {
"ENGINE": …
```
> feat: add certificate context filter

- eox_nelp/api_clients/__init__.py
- eox_nelp/api_clients/sms_vendor.py
- eox_nelp/api_clients/tests/test_sms_vendor.py
- eox_nelp/settings/test.py
feat: add SMS vendor client API
Set the following settings.
``` json
"SMS_VENDOR_URL": "https://example.com",
"SMS_VENDOR_SEND_SMS_PATH": "sendSMS", (Optional)
"SMS_VENDOR_USER": "test-user",
"SMS_VENDOR_PASSWORD" : "test-password",
"SMS_VENDOR_MSG_SENDER": "test-sender" (Optional)
```
The testing is waiting for the configuration of the vendor URL.
**Jira story**
https://edunext.atlassian.net/browse/FUTUREX-692
> feat: add SMS vendor client API

- .github/workflows/strain_dispatcher.yml
> feat: update target strain path

- eox_nelp/pearson_vue/rti_backend.py
- eox_nelp/pearson_vue/tasks.py
- eox_nelp/pearson_vue/tests/test_rti_backend.py
- eox_nelp/pearson_vue/tests/test_tasks.py
This add a class that executes pipeline steps and a general task that implements the mentioned class
1. Create a testing method
```
def test(pipeline_index, **kwargs):
print(pipeline_index)
```
2. include the test method in the pipeline list
```
def get_pipeline(self):
"""
Returns the RTI pipeline, which is a list of functions to be executed.
"""
return [
test,
test,
test,
test,
test,
test,
test,
]
```
3. Go to the lms shell `./manage.py lms shell`
4. import the task `from eox_nelp.pearson_vue.tasks import real_time_import_task`
5. call the task with some parameters `real_time_import_task.apply(user_id=1, course_id="hello")`
- Any special concerns or …
> feat: add pearson_vue module and rti backend

- eox_nelp/signals/tasks.py
- eox_nelp/signals/tests/test_tasks.py
- eox_nelp/signals/utils.py
This opens the door to the following PR:
https://github.com/eduNEXT/eox-nelp/pull/158
> refactor: reuse grading and completion logic

- eox_nelp/pearson_vue/pipeline.py
- eox_nelp/pearson_vue/tests/test_pipeline.py
- eox_nelp/settings/test.py
> feat: add ping, cdd and ead pipeline steps

- eox_nelp/api_clients/pearson_rti.py
This includes a inner method into auditable methods to avoid  JSON serializable errors
> fix: include inner wrapper to avoid  JSON serializable errors

- eox_nelp/pearson_vue/pipeline.py
- eox_nelp/pearson_vue/tests/test_pipeline.py
This add a new pipe that allows to get the exam data for a specific course
> feat: add get_exam_data pipe

- eox_nelp/api_clients/__init__.py
- eox_nelp/api_clients/tests/mixins.py
> fix: encoded body to utf-8 for arabic chars

- eox_nelp/pearson_vue/constants.py
- eox_nelp/pearson_vue/pipeline.py
- eox_nelp/pearson_vue/tests/test_pipeline.py
This add the client authorization id the EAD request
> feat: this includes the client authorization id into the EAD request

- eox_nelp/pearson_vue/constants.py
- eox_nelp/pearson_vue/pipeline.py
- eox_nelp/pearson_vue/tests/test_pipeline.py
- eox_nelp/pearson_vue/tests/test_utils.py
- eox_nelp/pearson_vue/utils.py
This is for pearson RTI ead request
Describe what this pull request changes, and why. Include implications for people using this change.
Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
> feat: user course enrollment for clientAuthID

- eox_nelp/admin/student.py
- eox_nelp/admin/tests/__init__.py
- eox_nelp/pearson_vue/pipeline.py
- eox_nelp/pearson_vue/rti_backend.py
- eox_nelp/pearson_vue/tasks.py
- eox_nelp/pearson_vue/tests/test_rti_backend.py
- eox_nelp/pearson_vue/tests/test_tasks.py
Go to course enrollment, check and test update EAD, add EAD, delete EAD.
Send CDD.
> feat: add ead and cdd task for admin panel

- eox_nelp/pearson_vue/pipeline.py
improve audit columns for person vue exceptions
> feat: improve audit columns

- eox_nelp/one_time_password/api/v1/tests/test_views.py
- eox_nelp/one_time_password/api/v1/views.py
- Activate Validate OTP in back and front. Settings
```json
"ENABLE_OTP_VALIDATION": true,
"MFE_CONFIG_MAP": {
"ENABLE_OTP_VALIDATION": "ENABLE_OTP_VALIDATION"
},
"REQUIRED_USER_PROFILE_FIELDS": [
"country",
"city",
"phone_number"
]
```
- Fill the phone_number in the user_data modal in a site.
- Check your phone for the Phone Validation Code.
- set the code  in the modal and check it works.
> feat: logic to send SMS for generante OTP

- eox_nelp/init_pipeline.py
- eox_nelp/tests/test_init_pipeline.py
Describe what this pull request changes, and why. Include implications for people using this change.
Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.
> fix: patch generate_password in loaded module

- eox_nelp/api_clients/pearson_engine.py
- eox_nelp/api_clients/tests/test_pearson_engine.py
> fix: set right endpoint

- eox_nelp/settings/common.py
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/pip-tools.txt
- requirements/test.txt
- requirements/tox.txt
Used the version of pydantic prod image.
> fix: ensure use the prod pydantic version

- eox_nelp/user_profile/api/v1/tests/test_views.py
- eox_nelp/user_profile/api/v1/views.py
This replace the cdd task in order to use the  V2 version that  uses the pearson engine microservice 
> feat: replace  cdd task in order to use the v2 version

- eox_nelp/api_clients/pearson_engine.py
- eox_nelp/api_clients/tests/test_pearson_engine.py
This adds the Arabic name to the engine user data request
> feat: add the Arabic name to the engine request user data

- eox_nelp/course_api/v1/serializers.py
- eox_nelp/course_api/v1/tests/test_views.py
- eox_nelp/edxapp_wrapper/backends/course_experience_p_v1.py
- eox_nelp/edxapp_wrapper/course_experience.py
- eox_nelp/edxapp_wrapper/test_backends/course_experience_p_v1.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
feat: add course_home_url to course_api
Go to `/eox-nelp/courses/v1/courses/` and check `course_home_url` attr in each course
> feat: add course_home_url to course_api

- eox_nelp/payment_notifications/templates/payment_notifications.html
- eox_nelp/payment_notifications/templates/payment_notifications_with_frame.html
fix!: redwood gettext for payment notifications
Create a payment notification in admin.
Activate in settings
`ENABLE_PAYMENT_NOTIFICATIONS = True`
render the dashboard page and check no error in redwood.
> fix!: redwood gettext for payment notifications

- .github/workflows/tests.yml
- tox.ini
feat: change python39 to python312 tests
> feat: change python39 to python312 tests

- eox_nelp/admin/__init__.py
- eox_nelp/settings/common.py
- eox_nelp/settings/test.py
Fix nelp admin load for user model.
Tested in stage
Use this command to check admin model loaded in user admin using django shell.
```python3
from django.contrib import admin
for model, model_admin in admin.site._registry.items():
print(f"Model: {model.__name__}, Admin Class: {model_admin.__class__.__name__}")
```
> fix: custom reg form app label to load

- requirements/base.in
- requirements/base.txt
- requirements/test.txt
- requirements/tox.txt
feat: add sqs client requirement
> feat: add sqs client requirement

- eox_nelp/admin/certificates.py
- eox_nelp/external_certificates/tasks.py
- eox_nelp/external_certificates/tests/tests_tasks.py
- eox_nelp/signals/receivers.py
- eox_nelp/signals/tasks.py
- eox_nelp/signals/tests/test_tasks.py
Move tasks related external_certificates to its own dir.
Test the same functionality of 
https://github.com/eduNEXT/eox-nelp/pull/260
Check the same behavior related to external certificates without changes.
> refactor: create external certificate own dir

- eox_nelp/external_certificates/tasks.py
fix: dont sent course_id object to sqs cert task
error sending course_id object in SQS trigger task.
Not error sending SQS trigger
> fix: dont sent course_id object to sqs cert task

- eox_nelp/course_experience/admin.py
- eox_nelp/external_certificates/admin.py
- eox_nelp/notifications/admin.py
This improve the behaviour of the admin loading users or course in edit way.
- course experience models -> author and course
- external_certificates ->user, and course
- notifications -> course
Go to eox-nelp and check course experience admin views and the way the show author and course
[Screencast from 12-05-25 17:09:45.webm](https://github.com/user-attachments/assets/670c6460-e8ec-44d4-a02d-e160fd923b0b)
**Jira story**: https://edunext.atlassian.net/browse/FUTUREX-1161?atlOrigin=eyJpIjoiMDVjMGQ2ZGMzMTU4NGFkZGFmMzY1YjE2ZTU2NWU4YzIiLCJwIjoiaiJ9
> feat: improve admin raw fields

- eox_nelp/signals/tests/test_utils.py
- eox_nelp/signals/utils.py
This change the expiration field for the payload to create external certificates.
Tested in stage
**jira story**: https://edunext.atlassian.net/browse/FUTUREX-1107
> chore: change expiration fields for certificates
