eox_nelp/admin/course_creators.py

Change the way to search the user in the add form for course creators.
Change to look-up button and not dropdown list.
https://docs.djangoproject.com/en/2.2/ref/contrib/admin/#django.contrib.admin.ModelAdmin.raw_id_fields

feat: change search button user-course-creator

---

eox_nelp/apps.py

When a course is deleted in the lms service the elasticsearch record is not deleted since that operation is performed by this method https://github.com/openedx/edx-platform/blob/open-release/maple.master/cms/djangoapps/contentstore/signals/handlers.py#L73 which is triggered by a signal however that receiver method is  not register because that belongs to the cms service. This change import the handler module in order to force the method registration.

feat: Import cms signals handler module in order to register receivers

---

eox_nelp/management/commands/eox_tenant_cache_programs.py
requirements/base.in

- This PR started in the following discussion.
https://github.com/eduNEXT/edunext-platform/pull/720
- The command to load cache programs using eox-tenant and routes is:
`./manage.py lms eox_tenant_cache_programs`
- This moves the base command to this eox_tenant implementation from https://github.com/openedx/edx-platform/blob/open-release/maple.master/openedx/core/djangoapps/catalog/management/commands/cache_programs.py to this approach.
You can check the differences here:
https://www.diffchecker.com/JelU5kQJ/
- From now is necessary to use eox-tenant in order to use eox-nelp
https://drive.google.com/drive/folders/1shgl1cmtEkzWmSJGmjsJoeok05jfbqAM

feat: add cache programs command using eox-tenant

---

eox_nelp/middleware.py

With this change, you only access the `extended_profile_field` but do not modify de label of `DEFAULT_EXTRA_FIELDS`.
This could be reached or cause the problem if `extended_profile_fields` you put a DEFAULT_EXTRA_FIELD so you override the label. 
For example, for `first_name` the label in code is`First Name` https://github.com/eduNEXT/edunext-platform/blob/ednx-release/mango.master.nelp/openedx/core/djangoapps/user_authn/views/registration_form.py#L875 and this is the translation that exists. If you added in the `extended_profile_field` list the label will be built with the var in capitalization:`First_name` but the translation for this doesn't exist. 
Also if only a tenant is configured wrong, the attr of `RegistrationFormFactory`is never updated or cached... …

feat: forbid change label of REGISTER_EXTRA_FIELD

---

eox_nelp/views.py

change the form in mfe config view of `pgn-color-primary-base`.

feat: change nesting  of `pgn-color-primary-base`

---

eox_nelp/views.py

Add mfe config map keys object `MAP_MFE_CONFIG_KEYS` .  With this mapping  the mfe config API will respond wit they key of the mapping `KEY_MFE_JS` and the value found in Django setting with the `KEY_SETTING_DJANGO`.
This only works for keys in the main level of the Django settings.
This is based on the following map:
``` js
MFE_CONFIG_MAP: {
"KEY_SETTING_DJANGO": "KEY_MFE_JS",
}
```
eg: 
``` js
"MFE_CONFIG_MAP": {
"favicon_path": "FAVICON_URL",
"logo_image_url": "LOGO_URL"
},
```

feat: add map_mfe_config_keys implementation

---

commitlint.config.js

Add base config for commit-lint msg. For commit lint action
https://github.com/wagoid/commitlint-github-action/tree/master#configfile
https://github.com/conventional-changelog/commitlint/blob/master/%40commitlint/config-conventional/index.js

feat: add base commit lint confi file for actions

---

eox_nelp/notifications/notify_course_due_date.py

Looking at this comment, I thing is useful the ability to use the properties of the DateTime object of `subsection_due_date` in the templates.
https://github.com/nelc/edunext-nelp-documentation/pull/5/files#r1183917662

chore: add more manipulation for subsection_due_date

---

eox_nelp/stats/templates/tenant_stats.html
eox_nelp/stats/tests/test_views.py
eox_nelp/stats/urls.py
eox_nelp/stats/views.py
eox_nelp/urls.py

This reverts commit d9090a88b16aa17a5db9b3e94a73088b9506b144.

Revert "feat: positive logic to the stats view"

---

eox_nelp/course_experience/api/v1/relations.py
eox_nelp/course_experience/api/v1/serializers.py

This change is applied to course-experience api.
The relations file inherit from json api relation but add the possibility to add some extra fields using a function. The function has to be passed through the new relation using `get_extra_fields` kwarg. There you can calculate a dict that would be added to corresponding relationhips field. The base json api only add `id` and `type`, with this change you cad add extra model attributes.
https://github.com/django-json-api/django-rest-framework-json-api/blob/main/rest_framework_json_api/relations.py#L255
Clone the repo and check anything is broken and the feedback API work with it same functionality.
**jira story**:
https://edunext.atlassian.net/jira/software/c/projects/FUTUREX/boards/36?modal=detail&selectedIssue=FUTUREX-459

feat: add extra fields options to relationships

---

eox_nelp/course_experience/api/v1/serializers.py
eox_nelp/utils.py
eox_nelp/views.py

This create the utils file in eox-nelp and also move the `map_instance_attributes_to_dict` to could be used by other subproject folders.
All functionality keep  working
** related jira story**:
https://edunext.atlassian.net/jira/software/c/projects/FUTUREX/boards/36?modal=detail&selectedIssue=FUTUREX-459

refactor: create utils file to share in project

---

eox_nelp/course_experience/api/v1/serializers.py
eox_nelp/course_experience/api/v1/tests/mixins_helpers.py

This add the possibility to configure the course_overview mapping and user mapping via django settings using
`COURSE_EXPERIENCE_SETTINGS`
Know you can configure the relationship extra field via settings in tenant config.
``` json
"COURSE_EXPERIENCE_SETTINGS": {
"COURSE_OVERVIEW_EXTRA_FIELD_MAPPING": {
"ultra_name": "courseultra",
"course_key": "instance__field"
},
"USER_EXTRA_FIELD_MAPPING": {
"mega_name": "userultra",
"user_key": "user__field"
}
}
```
Clone repo and add variable keys to configure course_experience_keys for relationship in tenant config as above.
**related jira story**:
https://edunext.atlassian.net/jira/software/c/projects/FUTUREX/boards/36?modal=detail&selectedIssue=FUTUREX-459

feat: add setting configuration for relationships

---

eox_nelp/api_clients/__init__.py
eox_nelp/api_clients/futurex.py
eox_nelp/api_clients/tests/__init__.py
eox_nelp/api_clients/tests/tests_futurex.py

This move the general logic from the FuturexAPIClient to a new Abstract class.

refactor: implementing abstract API class

---

eox_nelp/api_clients/__init__.py
eox_nelp/api_clients/certificates.py
eox_nelp/api_clients/futurex.py
eox_nelp/api_clients/tests/__init__.py
eox_nelp/api_clients/tests/tests_certificates.py
eox_nelp/api_clients/tests/tests_futurex.py
eox_nelp/settings/test.py

This is part of https://edunext.atlassian.net/browse/FUTUREX-478, basically this includes a new feature that is to use an API with basic authentication and makes a small refactor in order to have classes with different kind of authentication

feat: add api client based on basic authentication.

---

eox_nelp/api_clients/certificates.py
eox_nelp/api_clients/tests/tests_certificates.py
eox_nelp/signals/tests/test_utils.py
eox_nelp/signals/utils.py

This allow to set the `group_code` based on the settings
Issue https://edunext.atlassian.net/browse/FUTUREX-485

feat: allows to set a group code base on the course id

---

eox_nelp/api_clients/__init__.py
eox_nelp/api_clients/certificates.py
eox_nelp/api_clients/tests/tests_certificates.py
eox_nelp/api_clients/tests/tests_futurex.py

This allows to include header from the django settings in the api _client session https://edunext.atlassian.net/browse/FUTUREX-490

feat: adding extra headers feature.

---

eox_nelp/api_clients/__init__.py
eox_nelp/api_clients/certificates.py
eox_nelp/api_clients/tests/__init__.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tasks.py
eox_nelp/signals/tests/test_receivers.py
eox_nelp/signals/tests/test_utils.py
eox_nelp/signals/utils.py

Changes dateTime to date
Considers all the  2xx status codes
Improves response error logs

fix: changing date time to date and applying general imrpovements

---

eox_nelp/api_clients/certificates.py

This adds a prefix to the payload reference id parameter, I didn't include the host since I consider that information is not relevant because the certificate is not associated with a tenant, that is associated with a course and a course could be associated with multiple tenants

feat: add prefix to reference_id parameter in certificate api client

---

eox_nelp/api_clients/certificates.py

This allows to audit the `create_external_certificate` method
1.Set external certificates feature
2. Save a GeneratedCertificate in the admin panel
3. check /admin/eox_audit_model/auditmodel/  table

feat: allows to audit the create_external_certificates method

---

eox_nelp/admin/__init__.py
eox_nelp/admin/certificates.py
eox_nelp/edxapp_wrapper/backends/certificates_m_v1.py
eox_nelp/edxapp_wrapper/certificates.py
eox_nelp/edxapp_wrapper/test_backends/certificates_m_v1.py
eox_nelp/settings/common.py
eox_nelp/settings/test.py

Adds a new admin action class that allows to create external certificates, this logic came from the model implementation https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/certificates/models.py#L524 and the previous implemented celery task  https://github.com/eduNEXT/eox-nelp/blob/master/eox_nelp/signals/tasks.py#L140
Issue:
https://edunext.atlassian.net/browse/FUTUREX-486

feat: add new admin action that allows to create external certificates

---

eox_nelp/api_clients/certificates.py
eox_nelp/api_clients/tests/tests_certificates.py
eox_nelp/signals/tests/test_utils.py
eox_nelp/signals/utils.py
eox_nelp/utils.py

feat: add national_id validation for reference_id
Also, the shape of reference_id was updated adding the course_id. `{username}~{course_id}"`
Tested in stage debug server.
Main jira story parent
https://edunext.atlassian.net/browse/FUTUREX-471

feat: add national_id validation for reference_id

---

eox_nelp/admin/register_admin_model.py
eox_nelp/edxapp_wrapper/backends/certificates_m_v1.py

This fixes two things
1. This won't allow to register an admin model if the django app is not installed [eox_nelp/admin/register_admin_model.py](https://github.com/eduNEXT/eox-nelp/compare/and/fix_studio_admin?expand=1#diff-fe7f87f2f8d29360092bdc8483652a8371be8b968330d8f275c994001550237e)
2.  when the import` from lms.djangoapps.certificates import admin` is made in that way all registration processes inside that file are performed, so the import way is changed in order to avoid undesired registrations and before importing the admin model a django app validation is executed [eox_nelp/edxapp_wrapper/backends/certificates_m_v1.py](https://github.com/eduNEXT/eox-nelp/compare/and/fix_studio_admin?expand=1#diff-2ca90a23b1422824233f120b2e1fd242bfae3bcb81fd784d2c827867ee18844f)
1. check this …

fix: limit registration based on current installed apps

---

eox_nelp/apps.py
eox_nelp/edxapp_wrapper/test_backends/grades_m_v1.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tests/test_receivers.py
eox_nelp/signals/tests/test_utils.py
eox_nelp/signals/utils.py

This will create external certificates when a user enrolls in a course, generally that certificate will have a grade of 0 and then that will be updated by the certificate_publisher
https://edunext.atlassian.net/browse/FUTUREX-488
1. Set ENABLE_CERTIFICATE_PUBLISHER to True
2. Save a course enrollment in the admin panel, then check logs. Change the course enrollment mode to get different logs

feat: adding enrollment receiver

---

eox_nelp/admin/certificates.py

Shows generated errors during the create_external_certificate_action execution
Results

feat: displaying generated errors 

---

eox_nelp/auth_pipeline.py

This is an extension of `social_core.pipeline.social_auth.social_details` that allows to map response fields in standard user fields.
Part of https://edunext.atlassian.net/browse/FUTUREX-515
I tested this by adding the file to the debug server on production 
This change was required 
`AUTHENTICATION_BACKENDS.insert(0, "eox_core.social_tpa_backends.ConfigurableOpenIdConnectAuth")`

feat: add custom social_details pipeline

---

eox_nelp/edxapp_wrapper/backends/course_overviews_m_v1.py
eox_nelp/edxapp_wrapper/course_overviews.py
eox_nelp/edxapp_wrapper/test_backends/course_overviews_m_v1.py
eox_nelp/openedx_filters/tests/xapi/tests_filters.py
eox_nelp/openedx_filters/xapi/filters.py
eox_nelp/tests/test_utils.py
eox_nelp/utils.py

This filter allows to implement the required object structure by the NELC team https://edunext.atlassian.net/browse/FUTUREX-251
1. Use this version of event routing https://github.com/nelc/event-routing-backends/pull/5
2. add the settings        
```
OPEN_EDX_FILTERS_CONFIG = {
"event_routing_backends.processors.xapi.enrollment_events.base_enrollment.get_object": {
"pipeline": ["eox_nelp.openedx_filters.xapi.filters.XApiBaseEnrollmentFilter"],
"fail_silently": False,
},
}
```
3. This uses the language and the short_description studio fields, set them
4. Perform an enrollment or unenrollment event
5.  Check the result, in my case I'm using aspects, so I can check that in the superset panel
- Does this …

feat: add XApiBaseEnrollmentFilter

---

eox_nelp/processors/tests/xapi/event_transformers/tests_course_experience_events.py
eox_nelp/processors/tests/xapi/event_transformers/tests_initialized_events.py
eox_nelp/processors/tests/xapi/mixins.py
eox_nelp/processors/tests/xapi/tests_mixins.py
eox_nelp/processors/xapi/constants.py
eox_nelp/processors/xapi/event_transformers/__init__.py
eox_nelp/processors/xapi/event_transformers/course_experience_events.py
eox_nelp/processors/xapi/mixins.py

This pr adds new transformers for the events added in this [pr](https://github.com/eduNEXT/eox-nelp/pull/115)  the whole functionality depends on the previous pr however the code doesn't that's why this was not rebased over the code of the pr 115
1.  Ensure that you have the changes of the pr 115
2. Generate an event, use as guide the instructions of the pr 115 
3.  Verify the data that was sent, I use aspects

feat: add course experience transformer

---

eox_nelp/openedx_filters/tests/xapi/tests_filters.py
eox_nelp/openedx_filters/xapi/filters.py
eox_nelp/processors/xapi/constants.py

This updates the eox-nelp default language  in order to use that value on the filters where that constant is used, on the other hand implements a filter that update the verb language key
1. Set filter settings
```
OPEN_EDX_FILTERS_CONFIG = {
"event_routing_backends.processors.xapi.enrollment_events.base_enrollment.get_object": {
"pipeline": ["eox_nelp.openedx_filters.xapi.filters.XApiBaseEnrollmentFilter"],
"fail_silently": False,
},
}
```
2. Raise an event
3. Confirm verb dispaly key
- Link to other information about the change, such as Jira …

feat: Add verb filter and updates default language

---

eox_nelp/openedx_filters/tests/xapi/tests_filters.py
eox_nelp/openedx_filters/xapi/filters.py

This pr considers two things
1. the line `transformer.get_data('display_name')` obtains the value from the tracker [context](https://github.com/openedx/event-tracking/blob/706ac528d86962d5d4dedda992f609a06db042ff/eventtracking/tracker.py#L41)  however that context is not updated for the completion-aggregator library when the event is emitted  so as you can see in the following images  the context is the same for problems, verticals, sequentials and chapters 
After these changes the result is the following
2. Even if the context were updated that context just works on synchronous processes so this implementation contemplates async tasks
- Any special …

fix: get display name from module descriptor instead of tracker context

---

eox_nelp/edxapp_wrapper/backends/course_blocks_m_v1.py
eox_nelp/edxapp_wrapper/course_blocks.py
eox_nelp/edxapp_wrapper/test_backends/course_blocks_m_v1.py
eox_nelp/settings/common.py
eox_nelp/settings/test.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tasks.py
eox_nelp/signals/tests/test_receivers.py
eox_nelp/signals/tests/test_tasks.py

This includes the attempt's number in the subsection attempt event and small refactor
the refactor basically moves the logic from the receiver method to an async task, since to calculate the attempt's number requires iterate over all the subsection components
1. Go to a unit inside a graded subsection, a graded subsection is the one what was configure with the grade as parameter in studio
2. Check the logs
Expected result

feat: include attempts in subsection attempt event

---

eox_nelp/middleware.py

This reverts commit 50ee5441e76444b29600e6e8f07776a2339ab26a.
This is because we are using:
https://github.com/eduNEXT/eox-tenant/blob/v9.3.0/eox_tenant/middleware.py#L74
PR related:
https://github.com/nelc/manifest-sagar/pull/366

Revert "feat: add TenantExistMiddleware"

---

eox_nelp/middleware.py

Migrate the language per cookie usage from edx-platform to plugin.
This was inspired in the `COOKIES` manipulation by django.https://github.com/django/django/blob/main/django/core/handlers/wsgi.py#L100-L102
1. Checkout you edx-platform to `open-release/palm.nelp`.
2. Install eox-nelp using this branch or using editable way.
eg
```
pip install git+https://github.com/eduNEXT/eox-nelp.git@jlc/palm-mig/language-middleware --force-reinstall --no-deps
```
3. add the middleware in setting using the following config.
``` python
index_nelp_lang = index_nelp_lang = MIDDLEWARE.index("openedx.core.djangoapps.lang_pref.middleware.LanguagePreferenceMiddleware") + 1
MIDDLEWARE.insert(index_nelp_lang, "eox_nelp.middleware.PreserveUserLanguageCookieMiddleware")
```
[Screencast from 26-01-24 …

Jlc/palm mig/language middleware

---

eox_nelp/init_pipeline.py
eox_nelp/user_authn/utils.py
requirements/base.in
requirements/base.txt
requirements/constraints.txt
requirements/pip-tools.txt
requirements/test.txt
requirements/tox.txt

This PR is a monkey patch to generate_password.
This was a PR of edx-platform but now this is included in eox-nelp.
As the feature of the [PR](https://github.com/eduNEXT/edunext-platform/pull/676)  needs django-password-validators this PR add to eox-nelp the possibility to install it.
Also edx-django-utils is included in requirements, but is a normal package of edx-platform.
I added a logger to know that the password is generated via eox-nelp.
- install this package with this branch
- Configure auth password validators in settings with custom rules, you could use [this](https://github.com/nelc/manifest-sagar/blob/8b950ae70f66a0232a6f8336c3f6dfb421fffd74/environments/prod/openedx/env/base/apps/openedx/settings/lms/production.py#L332) as eg.
``` python
AUTH_PASSWORD_VALIDATORS = [
...
]
``` …

Jlc/palm mig/patch generate passwords

---

eox_nelp/edxapp_wrapper/test_backends/users_p_v1.py
eox_nelp/migrations/0001_initial.py
eox_nelp/settings/test.py
eox_nelp/stats/metrics.py
eox_nelp/stats/tests/tests_metrics.py

This adds users from user singup source records to the get_learners_metric result, basically this metric will take into account two conditions  user that are enrolled in a tenant course and users that completed the signup process at that tenant.
1. Go to `/eox-nelp/api/stats/v1/tenant/`
2. Check the value of the field learners
3. Verify that the returned value is  (Total of  enrollments for course of the current tenant ) + (Total of  signup source records that belong to the current tenant)
**Note**
The metric doesn't return duplicates, so if the user completed the signup process in the current tenant and has at least one enrollment, the metric will return  1
On development environments the signupsource records uses the port, probably you will have to remove that, since the …

feat: return signup source records in learner metrics

---

eox_nelp/pearson_vue/constants.py
eox_nelp/pearson_vue/tests/test_utils.py
eox_nelp/pearson_vue/utils.py
requirements/base.in
requirements/base.txt
requirements/test.txt

This PR add **xmltodict** package to add a dynamic way to update xml payloads.
The idea is to parse the xml string representation to dict representation. Then there update with the corresponding update_dict based in the tag purpose. Finally the dict representation is returned to the string representation.
There is a utils module  with 3 methods generated with the idea of modifying specific tags: 
- `<usernameToken>` -> update_payload_username_token
- `<scg:cddRequest>` -> update_payload_cdd_request
- `<scg:eadRequest>` -> update_payload_ead_request
So the 
This could be generalized, but I think that 3 is enough for this step.
Also, there is a constant file with the base xml string payloads for each use. I added with easier visual format.
Here is an example of the dict transform.
You could …

Jlc/pearson vue/payload manipulations

---

eox_nelp/apps.py
eox_nelp/pearson_vue/constants.py
eox_nelp/pearson_vue/pipeline.py
eox_nelp/pearson_vue/rti_backend.py
eox_nelp/pearson_vue/tests/test_pipeline.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tests/test_receivers.py

feat: configure receiver and pipe for completion and grade passed course.
Created 2 receivers one for block_completion post_save signal, and the other  `COURSE_GRADE_NOW_PASSED` signal.
Each one has a setting to manage.
- `PEARSON_RTI_ACTIVATE_COMPLETION_GATE`
- `PEARSON_RTI_ACTIVATE_GRADED_GATE`
Then is a pipeline(`handle_course_completion_status`) that analyzes whether to continue the pipeline in completion cases or not. This would be the first on the list.
The pipeline has 3 behaviors depending on the case:
- is_passing is true means the course is graded(passed) and doesn't need this pipe validation.
The pipeline continues without changes.
- is_complete=True and is_graded=False pipeline should continue with uploaded metadata
(completed courses and not graded).
- Otherwise, the pipeline …

Jlc/pearson vue/connect completion grading receivers

---

eox_nelp/one_time_password/api/v1/tests/test_views.py
eox_nelp/one_time_password/api/v1/urls.py
eox_nelp/one_time_password/api/v1/views.py
eox_nelp/one_time_password/view_decorators.py
eox_nelp/user_profile/api/v1/tests/test_views.py
eox_nelp/user_profile/api/v1/views.py

This removes the OTP validation logic from the user-profile view and creates a new view that implements a new decorator that executes the OTP validation
This doesn't modify the current behavior of update_user_data, so the first step is to verify that the implementation has not been modify
Make a POST request to `/eox-nelp/api/one-time-password/v1/validate/ `with the right  data, the code could be generated with the current endpoint `/eox-nelp/api/one-time-password/v1/generate/`
- Link to other information about the change, such as Jira issues, …

feat: extract validation otp from user-profile logic

---

eox_nelp/one_time_password/api/v1/views.py
eox_nelp/one_time_password/view_decorators.py
eox_nelp/tests/mixins.py

This makes optional the phone_number API parameter, by taking as default option the database information
1. Set the user phone number
2. Make a POST request with an empty body `/eox-nelp/api/one-time-password/v1/generate/`
3. Check logs and response

feat: set default phone number

---

eox_nelp/user_profile/api/v1/tests/test_views.py
eox_nelp/user_profile/api/v1/views.py

support missing user field in update_user_data API view
1. Add settings e,g
```python
EXTRA_ACCOUNT_USER_FIELDS = (
"first_name",
"last_name",
)
```
2. Go to /eox-nelp/api/user-profile/v1/update-user-data/
3. Send the field and check

feat: support missing user field in update_user_data API view

---

eox_nelp/pearson_vue/pipeline.py
eox_nelp/pearson_vue/rti_backend.py
eox_nelp/pearson_vue/tests/test_pipeline.py

This adds 2 pipeline steps independent to build
cdd_request and ead_request dicts.

refactor: split pipeline steps for cdd ead requests

---

eox_nelp/user_profile/api/v1/tests/test_views.py
eox_nelp/user_profile/api/v1/views.py

[feat: add cdd task to user updated profile api](https://github.com/eduNEXT/eox-nelp/commit/3a42dd98d955d874b70831181b7f4af2617f1d15)
Update your profile using profile API or using bragi modal.
Check the cdd_task is triggered.
Check audit record was sent.

feat: add cdd task to user updated profile api

---

eox_nelp/pearson_vue/exceptions.py
eox_nelp/pearson_vue/pipeline.py
eox_nelp/pearson_vue/tests/test_pipeline.py

](refactor: use PearsonImportError for imports)[refactor: use PearsonImportError for imports](https://github.com/eduNEXT/eox-nelp/pull/185/commits/8a67baf040b7d57657295901b454329db82d92f9)
Send a CDD or EAD that would fail due wrong configurations.
Error import is only tried once.
Pearson import error exception raised.
Update before add .

refactor: use PearsonImportError for imports

---

eox_nelp/pearson_vue/rti_backend.py
eox_nelp/pearson_vue/tests/test_rti_backend.py

Refactor that implements a backend abstract class, basivally this moves the handler error logic to a new method that could be overridden by any subclass

refactor: implement abstract backend class

---

eox_nelp/one_time_password/view_decorators.py
eox_nelp/tests/test_utils.py
eox_nelp/user_profile/api/v1/tests/test_views.py
eox_nelp/user_profile/api/v1/views.py
eox_nelp/utils.py

Add extrainfo change capability with user profile data.
Use post to `{lms_domain}/eox-nelp/api/user-profile/v1/update-user-data/` and update extrainfo data
[Screencast from 10-07-24 17:13:25.webm](https://github.com/eduNEXT/eox-nelp/assets/51926076/e5fbfd34-0e6a-4581-9a9c-1a81f0ff236d)

feat: profile api save extrainfo arabic fields

---

eox_nelp/pearson_vue/decorators.py
eox_nelp/pearson_vue/pipeline.py
eox_nelp/pearson_vue/rti_backend.py
eox_nelp/pearson_vue/tests/test_rti_backend.py

feat: add audit for succesfull imports

---

eox_nelp/api_clients/authenticators.py
eox_nelp/api_clients/sms_vendor.py
eox_nelp/api_clients/tests/test_sms_vendor.py
eox_nelp/settings/test.py

refactor: sms vendor with notification-gateway api
- Use your local cli.
- Set credentials in settings, and init one SMSVendorApiClient
- Send an sms to a recipient you know.
- Check your phone if you received the msg.

refactor: sms vendor with notification-gateway api

---

eox_nelp/pearson_vue/pipeline.py
eox_nelp/pearson_vue/tests/test_pipeline.py

feat: elegibility_appt_dates runtime calculations in exam_metadata.
- Send an EAD request.
- Check the keys sent in the ead_request object. Those keys would be calculated based on "now" (eligibility_appt_date_first) and one year after (eligibility_appt_date_last).
```
eligibility_appt_date_first
eligibility_appt_date_last
```
Check in audit the update data.

feat: elegibility_appt_dates runtime calculations

---

eox_nelp/pearson_vue/rti_backend.py

Deactivate audit process, since the backend has data that is not serializable 

fix: turn off audit feature

---

eox_nelp/pearson_vue/api/v1/serializers.py

This changes the candidate representation from id to username

feat: change candidate representation from id to username

---

eox_nelp/apps.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tests/test_receivers.py

feat: userSignUpSource created by course_enrollment
Configure signal after a courseEnrollment save to create the desired UserSignUpSource record based on the course_enrollment using the org course.
1. Go to UserSignUpSource in admin and select a user.
2. Go to course_enrollment in admin and select a course_enrollment related to the user and a course with an org-related site that doesn't have a UserSignUpSource record. Save the course_enrollment.
3. Check logs or check that the UserSignUpSource record was created.

feat: userSignUpSource create by course_enrollment

---

eox_nelp/pearson_vue/api/v1/views.py
eox_nelp/pearson_vue/tests/api/v1/test_views.py
eox_nelp/settings/test.py

This PR introduces improvements to the API enablement logic within an inherited view, specifically in the dispatch and is_api_enabled methods. These changes allow more granular control over API access based on the request type (GET or POST), managed by specific settings.
- The dispatch method has been updated to use the new is_api_enabled method instead of a simple check for a single setting (PEARSON_RTEN_API_ENABLED).
- Now, if the API is not enabled according to the new request method-specific settings (PEARSON_RTEN_API_WRITE_ENABLED and PEARSON_RTEN_API_READ_ENABLED), an Http404 exception is raised.
- Any special concerns or limitations? For example: …

feat: split feature flag into read and write permissions

---

eox_nelp/api_clients/authenticators.py
eox_nelp/api_clients/futurex.py
eox_nelp/api_clients/pearson_engine.py
eox_nelp/api_clients/tests/mixins.py
eox_nelp/api_clients/tests/test_pearson_engine.py
eox_nelp/settings/test.py

This adds a new client that allows to connect with the rti service provided by this [pr](https://github.com/nelc/pearson_vue_engine/pull/11)
https://edunext.atlassian.net/browse/FUTUREX-830
1. Add the following settings
```python
PEARSON_ENGINE_API_CLIENT_ID = "blablba"
PEARSON_ENGINE_API_CLIENT_SECRET = "fsdfsdf"
PEARSON_ENGINE_API_URL = "http://example.com"
```
2. Run into a shell
```python
from eox_nelp.api_clients.pearson_engine import PearsonEngineApiClient
from django.contrib.auth import get_user_model
api_client = PearsonEngineApiClient()
User = get_user_model()
user = User.objects.get(id=<your id>)
api_client.import_candidate_demographics(user)
api_client.import_exam_authorization(user, "course_id")
```
Include anything else that will help reviewers and consumers understand the …

feat: add Pearson engine client

---

eox_nelp/admin/student.py
eox_nelp/admin/tests/__init__.py
eox_nelp/pearson_vue/constants.py
eox_nelp/pearson_vue/tasks.py
eox_nelp/pearson_vue/tests/test_tasks.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tests/test_receivers.py

Adds a new celery task that allows to connect previous integration with the pearson engine service. 
1. Go to current course enrollment implementation  and test all the custom actions

feat: implement new celery task for pearson engine integration

---

eox_nelp/pearson_vue/tasks.py
eox_nelp/pearson_vue/tests/test_tasks.py

Raise an exception to enable the fail case on eox-audit-mode when the response contains an error, this also limits the retry scenario to Timeout or connection error 
Useful information to include:
- Include screenshots for changes to the UI (ideally, both "before" and "after" screenshots, if applicable).
- Provide links to the description of corresponding configuration changes. Remember to correctly annotate these
changes.

feat: raise exception on api response error

---

eox_nelp/signals/receivers.py
eox_nelp/signals/tests/test_receivers.py

Check the existence of course-config for the processed course_id.
If there is not course-config (`PEARSON_RTI_COURSES_DATA`) for the desired course,
RTI requests would not be sent.
Refactored a little the tests.
**[Jira story](https://edunext.atlassian.net/browse/FUTUREX-877?atlOrigin=eyJpIjoiMjNiMzZmNmU3ZWU4NDhmNzg0N2EzNTM4ZmNkZDg3MTkiLCJwIjoiaiJ9)**:

fix: not start rti tasks if not course-config

---

eox_nelp/admin/student.py
eox_nelp/admin/tests/__init__.py

This removes the old pearson vue admin implementation in favor of the pearson engine feature, this also allow to control  the action visibility based on the `USE_PEARSON_ENGINE_SERVICE` value
1. Set the setting `USE_PEARSON_ENGINE_SERVICE` to false 
2. Go to  `/admin/student/courseenrollment/`
3.  Check that there are no actions
4. Set the setting `USE_PEARSON_ENGINE_SERVICE` to true 
5. Go to  `/admin/student/courseenrollment/`
6. Check that the Pearson actions appear

feat:  restrict admin actions based on the settings configuration.

---

eox_nelp/processors/tests/xapi/mixins.py
eox_nelp/signals/receivers.py
eox_nelp/signals/tasks.py
eox_nelp/signals/tests/test_receivers.py
eox_nelp/signals/tests/test_tasks.py
eox_nelp/signals/tests/test_utils.py
eox_nelp/signals/utils.py

This replaces the username references with the  extrainfo national id field 

feat: replace username with extrainfo national_id

---

eox_nelp/api_clients/pearson_engine.py
eox_nelp/api_clients/tests/test_pearson_engine.py

This adds the national id to the user_data which is send to the Pearson engine service 

feat: send national id to pearson engine service

---

eox_nelp/api_clients/pearson_engine.py

This modification adds a condition to the national_id key, if the value is empty that won't be sent 

fix: don't send empty national ids

---

.github/workflows/tests.yml

This PR upgrades the Github cache action version from `v3.2.3` to `v4`.

fix: upgrade github action cache version

---

eox_nelp/pearson_vue/tests/test_utils.py
eox_nelp/pearson_vue/utils.py

This PR updates the `get_user_data` method to include the new `full_name` attribute.
**IMPORTANT** please take a look at #245, its changes are necessary for this feature to work correctly.
- Added the `full_name` attribute to the pearson vue engine request.
- Update the `get_user_data` unit tests.
Did a recent request to pvengine stage to check it works correctly.

feat: add full name attribute to pearson vue request

---

eox_nelp/tests/test_validators.py
eox_nelp/user_profile/required_fields_validation.py
eox_nelp/user_profile/tests/test_required_fields_validation.py
eox_nelp/validators.py
requirements/base.in
requirements/base.txt
requirements/test.txt
requirements/tox.txt

This PR adds a method for validating user fields based on the REQUIRED_USER_FIELDS setting.
The validation ensures that each field meets the specified constraints, such as max_length, char_type, format, and optional_values.
Implemented validate_required_user_fields, which checks user fields against predefined validation rules.
Added specific validation methods for max_length, char_type, format, and optional_values.
Integrated structured settings to define required fields.
Added unit tests to ensure correct validation behavior.
1. Ensure the following setting is configured 
```
REQUIRED_USER_FIELDS = {
"account": {
"first_name": {"max_length": 30, "char_type": "latin"},
"last_name": {"max_length": 50, "char_type": "latin"},
},
"profile": {
"city": {"max_length": 32, "char_type": "latin"}, …
```

feat: add required fields validation logic

---

eox_nelp/user_profile/api/v1/tests/test_views.py
eox_nelp/user_profile/api/v1/urls.py
eox_nelp/user_profile/api/v1/views.py

Adds a new view that allows to get field validation base on `REQUIRED_USER_FIELDS` setting
1. First the `REQUIRED_USER_FIELDS` setting
```
REQUIRED_USER_FIELDS = {
"account": {
"first_name": {"max_length": 30, "char_type": "latin"},
"last_name": {"max_length": 50, "char_type": "latin"},
},
"profile": {
"city": {"max_length": 32, "char_type": "latin"},
"country": {"max_length": 2, "optional_values": ["US", "CA", "MX", "BR"]},
"phone_number": {"max_length": 15, "format": "phone"},
"mailing_address": {"max_length": 40},
},
"extra_info": {
"arabic_name": {"max_length": 20, "char_type": "arabic"},
"arabic_first_name": {"max_length": 20, "char_type": "arabic"},
"arabic_last_name": {"max_length": 50, "char_type": "arabic"},
},
}
```
2. Go to `/eox-nelp/api/user-profile/v1/validated-fields/`
3. …

feat: add get validated user fields view

---

eox_nelp/user_profile/required_fields_validation.py
eox_nelp/user_profile/tests/test_required_fields_validation.py

This PR introduces support for the allow_empty attribute in field validation, ensuring that fields explicitly marked with allow_empty: True do not trigger "Empty field" errors. Fields without this attribute or with allow_empty: False will continue to be validated as required.
- Updated validate_field to check for the allow_empty rule before applying other validations.
- Adjusted test cases to cover different scenarios for allow_empty (e.g., empty values with and without the rule).
- Minor refactor in test structure to ensure clarity in validation behaviors.
1. Add settings
```
REQUIRED_USER_FIELDS = {
"account": {
"first_name": {"max_length": 30, "char_type": "latin"},
"last_name": {"max_length": 50, "char_type": "latin"},
"invalid_field": {"max_length": 50, "char_type": "latin"},
}, …
```

feat: add support for allow_empty and enhance field validation tests

---

Makefile
eox_nelp/cms/api/urls.py
eox_nelp/cms/api/v1/tests/test_views.py
eox_nelp/cms_urls.py
eox_nelp/course_api/urls.py
eox_nelp/course_api/v1/serializers.py
eox_nelp/course_api/v1/tests/test_views.py
eox_nelp/course_experience/api/urls.py
eox_nelp/course_experience/api/v1/views.py
eox_nelp/course_experience/frontend/tests/test_views.py
eox_nelp/course_experience/frontend/views.py
eox_nelp/init_pipeline.py
eox_nelp/management/commands/notify_course_due_dates.py
eox_nelp/management/commands/tests/test_check_notify_course_due_dates.py
eox_nelp/one_time_password/api/urls.py
eox_nelp/one_time_password/api/v1/tests/test_views.py
eox_nelp/openedx_filters/xapi/filters.py
eox_nelp/payment_notifications/urls.py
eox_nelp/pearson_vue/api/urls.py
eox_nelp/pearson_vue/tests/test_pipeline.py
eox_nelp/pearson_vue/utils.py
eox_nelp/stats/api/urls.py
eox_nelp/stats/tests/test_views.py
eox_nelp/stats/tests/tests_metrics.py
eox_nelp/urls.py
eox_nelp/user_profile/api/urls.py
eox_nelp/user_profile/api/v1/tests/test_views.py
setup.cfg

This PR enables the [Pylint's useless suppression validation](https://pylint.readthedocs.io/en/v3.3.3/user_guide/messages/information/useless-suppression.html).  This rule reports when a message is explicitly disabled for a line or a block of code, but never triggered.  It was implemented as shown in Pylint's docs.
- Remove any unused validations suppressed through the entire project in f978201
- Change the `makefile` and `setup.cfg` for further validations in bfbc460
After locally executing `make quality` changes seems to be ok.
>[!NOTE]
>
>Even though multiple files were affected, I only removed the useless suppressions; no major changes were applied.

feat: remove pylint useless suppressions

---

eox_nelp/one_time_password/api/v1/tests/test_views.py
eox_nelp/one_time_password/api/v1/views.py
eox_nelp/pearson_vue_engine/tasks.py
eox_nelp/signals/tasks.py
eox_nelp/signals/tests/test_tasks.py
requirements/base.in
requirements/base.txt
requirements/test.txt

This PR updates the external-api-clients package to the latest version. The upgrade required several adjustments to constructor calls throughout the codebase.
* Unpinned external-api-clients package dependency
* Modified all of the clients constructor parameters to match the new required signature
* Added @override_settings decorators to provide required configuration in test environments
Follow the instructions from #249 for local setup. 
After completing a course an RTI request will be sended. 
The Badrequest response is enough to test the service call.

feat: unpin external-api-clients package

---

eox_nelp/user_profile/required_fields_validation.py
eox_nelp/user_profile/tests/test_required_fields_validation.py

This PR introduces support for the dependent_fields validation rule in the user field validation logic. This enhancement allows a field's valid values to be conditional on another field’s value.
- Implemented validate_dependent_field to check if a field's value adheres to constraints based on the values of other related fields.
- Updated validate_user_fields to incorporate validate_dependent_field.
- Extended the REQUIRED_USER_FIELDS structure to support dependent_fields, enabling rules where one field's valid values depend on another.
1. Add settings e.g
``` python
REQUIRED_USER_FIELDS = {
"account": {
"first_name": {"max_length": 30, "char_type": "latin"},
"last_name": {"max_length": 50, "char_type": "latin"},
"invalid_field": {"max_length": 50, "char_type": "latin"},
},
"profile": { …
```

feat: add support for dependent_fields validation

---

eox_nelp/admin/user.py
eox_nelp/edxapp_wrapper/backends/django_comment_common_r_v1.py
eox_nelp/edxapp_wrapper/backends/user_api_m_v1.py
eox_nelp/edxapp_wrapper/django_comment_common.py
eox_nelp/edxapp_wrapper/test_backends/django_comment_common_r_v1.py
eox_nelp/edxapp_wrapper/test_backends/user_api_m_v1.py
eox_nelp/edxapp_wrapper/user_api.py
eox_nelp/settings/common.py
eox_nelp/settings/test.py

This pull request introduces a new Django admin action named retire_users to the NelpUserAdmin class. This feature enables administrators to retire selected users directly from the Django admin interface
- Appends a timestamped suffix to the user's email and username to mark the retirement.=
- Deactivates the user account and creates a retirement request using the user API.
- Deletes any associated ExtraInfo records from custom_reg_form.models.
- Calls the forum service (via comment_client) to retire the user from the comment system.
- Catches RetirementStateError if a user is already retired and logs it via admin messages.
- Gracefully handles 404 errors from the forum service when the user record is missing.
- Catches and reports any unexpected exceptions during the process.
- Updated …

feat: create retire user admin action

---

eox_nelp/signals/tasks.py
eox_nelp/signals/tests/test_tasks.py

Adds a new log line to update_mt_training_stage to include the full API response.
Also updates the corresponding unit test to assert the exact INFO log output.
This ensures traceability of the response returned by the external service and improves confidence through explicit log validation.

feat: log update_mt_training_stage response and verify it in test
